"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1ADs2FRNaQg
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { toast } from "sonner";

export function LoginComp() {
  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });

  const handleInputChange = (e: { target: { name: any; value: any; }; }) => {
    const { name, value } = e.target;
    setFormData((prevFormData) => ({
      ...prevFormData,
      [name]: value,
    }));
  };

  const handleSubmit = async (e: { preventDefault: () => void; }) => {
    e.preventDefault();
    console.log("Login Form Data", formData);
    // Handle login logic here, such as calling an API to authenticate the user
    if(formData.email === "" || formData.password === "") {
      toast.error("Error", {
        description: "Please fill all fields to login.",
        action: {
          label: "Okay",
          onClick: () => console.error("No Data"),
        },
      })
      return;
    }else{
      toast.success("Success", {
        description: "Logged in successfully",
        action: {
          label: "Okay",
          onClick: () => {
            console.log("Logged in successfully");
          }
        },
      })
    }
  };

  return (
    <form onSubmit={handleSubmit} className="mx-auto max-w-sm">
      <Card>
        <CardHeader className="space-y-1">
          <CardTitle className="text-2xl font-bold">Login</CardTitle>
          <CardDescription>
            Enter your email and password to login to your account
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                name="email"
                placeholder="m@example.com"
                type="email"
                value={formData.email}
                onChange={handleInputChange}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                name="password"
                type="password"
                value={formData.password}
                onChange={handleInputChange}
              />
            </div>
            <Button className="w-full" type="submit">
              Login
            </Button>
          </div>
          <div className="flex justify-end items-center mt-4">
            <span className="text-sm">Dont have an account?</span>
            <a href="/register" className="text-sm text-primary-500">
            {" "}Register here
            </a>
          </div>
        </CardContent>
      </Card>
    </form>
  );
}
